### ISSUE TITLE
How to turn off SIP?

### ISSUE THREAD

**Issue by St0nehead** [MikeBeaton/macos-boot-helper#1]
macOS NURAM Boot Helper
0.1.0
boot-args="-no_compat_check" (persistent)
csr-active-config=0x00000077 (persistent)
StartupMute: EFI_NOT_FOUND
boot-[A]rgs;
[B]ig Sur: [C]atalina: Startup[M]ute
[R]eboot: [S]hutdown: [E]xit; [L]ist

Couldn't change 'csr-active-config' option.
MacPro 5.1, Catalina 10.5.7 (dosdude patched)

**Comment by mikebeaton** [comment]
Well press 'C' (to toggle 0x77 for Catalina).

If you mean that keyboard input doesn't work at all, then that's possible. I haven't worked on this much since working more on OpenCore, and it does not currently support anything other than basic EFI input, which needs to work out-of-the-box on your system, i.e. you can't use the various keyboard drivers OC provides.

You might be better off using the ToggleSIP feature of OpenCore?
